test-2

diff --git a/stats/stats b/stats/stats
--- a/stats/stats
+++ b/stats/stats
@@ -18,8 +18,13 @@
 
 
 
-# *** constants ***
-CFG_LOCATION=/home/$(whoami)/.config/stats.cfg
+# *** positions & constants ***
+SCRIPT_LOCATION=$(realpath "$0")
+WORK_LOCATION=$(dirname "$SCRIPT_LOCATION")
+MOTIV_LOCATION=$(dirname "$WORK_LOCATION")
+CFG_LOCATION=$WORK_LOCATION/stats.cfg
+BIN_LOCATION=$MOTIV_LOCATION/build/motiv
+GIT_AVAILABLE=true;
 DATE_FORMAT="%Y-%m-%d@%H-%M-%S"
 RED=`tput setaf 1`
 GREEN=`tput setaf 2`
@@ -55,8 +60,8 @@ trap 'error_line ${LINENO}' ERR
 # we probably don't want to keep logs from situations like "ctrl+c"-ed runs
 clean_up_full() {
     exitcode=$?
-    if [ -f "tmpfile@$file_name" ] && [ "$memory" = "1" ]; then
-        rm tmpfile@$file_name
+    if [ -f "$WORK_LOCATION/tmpfile@$file_name" ] && [ "$memory" = "1" ]; then
+        rm $WORK_LOCATION/tmpfile@$file_name
     fi
     if [ -f "$file_name" ] && [ "$dbg_info" = "0" ] && [ "$exitcode" -gt 0 ]; then
         rm $file_name
@@ -129,8 +134,8 @@ dbg_info=1
 dbg_log=""
 # how many >>%h%v%u%<< do we have?
 triplet_count=2
-# where do we want to save the results? ("" <=> same dir as stats)
-res_path=""
+# where do we want to save the results? (default choice: same dir as stats)
+res_path=$WORK_LOCATION
 # how many arguments do we have?
 argc=$#
 # how many samples do we want? (first argument)
@@ -198,8 +203,8 @@ read_all_nonflag_params() {
     fi
     if [ -n "$res_path_new" ]; then
         if [ "$res_path_new" == "\"\"" ] ; then
-            # "" means, we want to save the results to the same directory as stats
-            res_path=""
+            # "" means, we want to save the results to default choice
+            res_path=$WORK_LOCATION
         else
             if [ -d "$res_path_new" ]; then
                 res_path=$res_path_new
@@ -254,7 +259,7 @@ if [ "$1" = "-c" ] || [ "$1" = "--calibration" ]; then
     conditional_clear
     if ! [ -f "$CFG_LOCATION" ]; then
         echo -e "${YELLOW}${BOLD}Info${NOFORMAT}: could not find the config file ${CFG_LOCATION} for stats, will create a default config..."
-        echo -e "# do we want to measure memory use? (0 <=> no)\nmemory=0\n# how many seconds have to pass between the start of motiv and the memory snapshot via smem?\ngrace_period=2\n# amount of decimal places after the decimal point\nprecision=3\n# do we want to see debug information? (0 <=> no)\ndbg_info=0\n# how many >>%h%v%u%<< do we have?\ntriplet_count=2\n# where do we want to save the results? ("" <=> same dir as stats)\nres_path=\"\"" >> $CFG_LOCATION
+        echo -e "# do we want to measure memory use? (0 <=> no)\nmemory=0\n# how many seconds have to pass between the start of motiv and the memory snapshot via smem?\ngrace_period=2\n# amount of decimal places after the decimal point\nprecision=3\n# do we want to see debug information? (0 <=> no)\ndbg_info=0\n# how many data "units" does a <motiv -t [path]>-run produce? (1.0.0 has no stats support; version 1.0.1 up to at least 2.1.1 => 2)\ntriplet_count=2\n# where do we want to save the results? (\"\" <=> default choice: same dir as stats)\nres_path=\"\"" >> $CFG_LOCATION
         echo -e "[-/6] Do you wish to proceed with the calibration of the newly created <stats.cfg>? (${BOLD}${GREEN}Y${NOFORMAT}/${BOLD}${RED}N${NOFORMAT})"
         echo ""
         read -p "" -n 1 answer1
@@ -320,7 +325,7 @@ if [ "$1" = "-c" ] || [ "$1" = "--calibration" ]; then
     conditional_clear
     echo ""
     while true; do
-        echo -e "$CALIBRATION_QUESTION_5\n      -> Example (too small): %h1%v1%u1%%h2%v2%u2%%h3%v3%u3% with the value 2 is going to make stats to collect the data for %h1...% up until only %h2...%\n      -> Hint: stats will simply crash if the value is too big"
+        echo -e "$CALIBRATION_QUESTION_5\n      -> Example: %MainWindow::loadTrace()%4%ms%%application in general%73%ms%%\n      -> Hint: the default value for Motiv is 2\n      -> Hint: too small => stats will ignore some data; too big => stats will crash"
         echo ""
         read -p "Answer: " answer5
         if test $answer5 -ge 1 ; then
@@ -368,10 +373,19 @@ else
     # we have a regular stats run
     check_config
     read_all_nonflag_params
-    check_smem
+    if [ "$memory" -ne 0 ]; then
+        check_smem
+    fi
 fi
 
 # *** basic crital errors ***
+# can't find motiv
+if ! [ -f "$BIN_LOCATION" ] 2> /dev/null; then
+    conditional_clear
+    echo "${BG_RED}${BOLD}Critical${NOFORMAT}: can't find motiv, expected in: "$BIN_LOCATION
+    echo "          -> more details via -h/--help"
+    exit 1
+fi
 # FAQ: Q1
 # no sample size
 if ! [ "$count" -gt 0 ] 2> /dev/null; then
@@ -490,7 +504,7 @@ do
     	fi
     	
     	# we collect the raw data
-    	output_time=$(time (./build/motiv -t $cur_path 2>/dev/null) 2>&1)
+    	output_time=$(time ($BIN_LOCATION -t $cur_path 2>/dev/null) 2>&1)
     		
     	# that's the array pattern: e(mpty) h(int) v(value) u(unit), e h v u ... time values (user, real, sys)
     	# FAQ: Q4
@@ -502,11 +516,11 @@ do
                
         # RAM usage review
         if [ "$memory" -ne 0 ]; then
-            ./build/motiv $cur_path 2>> tmpfile@$file_name &
+            $BIN_LOCATION $cur_path 2>> $WORK_LOCATION/tmpfile@$file_name &
             prog_pid=$!
             sleep 2
             while true; do
-                if grep -q "motiv ready" tmpfile@$file_name; then
+                if grep -q "motiv ready" $WORK_LOCATION/tmpfile@$file_name; then
                     break
                 fi
             done
@@ -556,7 +570,7 @@ do
             else
                 conditional_clear
                 if [ $val_pos -gt ${#ehvu_array[@]} ]; then
-                    echo "${BG_RED}${BOLD}Critical${NOFORMAT}: out of bound regarding the value array, please check wether <triplet_count=...> in corresponds to the true amount of %h%v%u%-data triplets produced via <./motiv -t [trace]>-runs"
+                    echo "${BG_RED}${BOLD}Critical${NOFORMAT}: out of bound regarding the value array, please check wether <triplet_count=...> in $CFG_LOCATION corresponds to the true amount of %h%v%u%-data triplets produced via <./motiv -t [trace]>-runs"
                 else
                     echo "${BG_RED}${BOLD}Critical${NOFORMAT}: unkown time unit <${RED}${ehvu_array[$(($val_pos+1))]}${NOFORMAT}>, that happend for the ${j}. trace in the ${p}. iteration for the ${q}. sum/metric <${BG_YELLOW}${BOLD}${ehvu_array[$(($val_pos-1))]}${NOFORMAT}>"
                 fi
@@ -645,29 +659,43 @@ done
 
 
 # *** context-information ***
-if [ -n "$(whereis -b git | cut -d ' ' -f 2)" ]; then
-    git fetch
-    git_info="\nGIT\nRepo URL:\t"$(git remote get-url origin)
+if [ "$GIT_AVAILABLE" = true ]; then
+    no_errors=true;
+    git_info="\nGIT\n"
+    if ! [ -n "$(whereis -b git | cut -d ' ' -f 2)" ]; then
+        git_info="\ncan't find git\n!"
+        no_errors=false;
+    fi
+    if ! [ -d "$MOTIV_LOCATION/.git" ]; then
+        git_info="\ncan't find .git in "$WORK_LOCATIO"\n"
+        no_errors=false;
+    fi
+    if [ "$no_errors" = true ]; then
+        git -C $MOTIV_LOCATION fetch
+        git_info=$git_info"Repo URL:\t\t"$(git -C $MOTIV_LOCATION remote get-url origin)
 
-    # what branch do we test?
-    git_branch=$(git branch --show-current)
-    git_info=$git_info"\nBranch:\t\t"$git_branch
+        # what branch do we test?
+        git_branch=$(git -C $MOTIV_LOCATION branch --show-current)
+        git_info=$git_info"\n\nBranch:\t\t\t"$git_branch"\n"
 
-    # documentation of the development status
+        # documentation of the development status
 
-    # we assume that $(git rev-parse HEAD) represents the current used revision
-    git_local_commit_hash=$(git rev-parse HEAD)
+        # we assume that $(git rev-parse HEAD) represents the current used revision
+        git_local_commit_hash=$(git -C $MOTIV_LOCATION rev-parse HEAD)
 
-    # do we have any changes relative to the most recent branch commit?
-    git_info=$git_info"\n\t\t-> any difference to the latest commit?\n"$git_last_commit$(git diff --stat $git_branch | sed 's/ /\t\t/')
+        # do we have any changes relative to the most recent branch commit?
+        git_info=$git_info"\n\t\t-> any difference to the latest commit?\n"$git_last_commit$(git -C $MOTIV_LOCATION diff --stat $git_branch | sed 's/ /\t\t/')
 
-    git_info=$git_info"\n\nHEAD (Hash):\t"$git_local_commit_hash
-    # do we have any changes relative to the used "version" of our branch?
-    git_info=$git_info"\n\t\t-> any difference to the used revision?\n"$(git diff --stat $git_local_commit_hash | sed 's/ /\t\t/')
+        git_info=$git_info"\n\nHEAD (Hash):\t"$git_local_commit_hash
+        # do we have any changes relative to the used "version" of our branch?
+        git_info=$git_info"\n\n\t\t-> any difference to the used revision?\n"$(git -C $MOTIV_LOCATION diff --stat $git_local_commit_hash | sed 's/ /\t\t/')
+    fi
 fi
 
 echo -e "\n\n\n" >> $path_plus_file_name
 echo -e "***************************\n*** context information ***\n***************************" >> $path_plus_file_name
+echo -e "\n"$($BIN_LOCATION --version) >> $path_plus_file_name
+echo -e $git_info >> $path_plus_file_name
 echo -e "\nOS\n"$(uname -a) >> $path_plus_file_name
 echo -e "\nCPU\n"$(lscpu | grep "Model name:" | sed -r 's/Model name:\s{1,}//g') >> $path_plus_file_name
 # this is an alternative to echo, the upside is that we can keep the format of $(free -h)
@@ -676,17 +704,15 @@ cat <<EOF >> $path_plus_file_name
 RAM
 $(free -h)
 EOF
-echo -e "\nSAMPLE SIZE\n"$count"#" >> $path_plus_file_name
-echo -e $git_info >> $path_plus_file_name
-echo -e "\nSAMPLE-LOG\n"$log >> $path_plus_file_name
 
+echo -e "\nSAMPLE-LOG\nSample size:\t"$count"# (measurements per tracefile)\n"$log >> $path_plus_file_name
 
 # *** final exit ***
 conditional_clear
 echo "${BOLD}stats${NOFORMAT}: ${BG_CYAN}${path_plus_file_name}${NOFORMAT}"
 # small clean up
 if [ "$memory" = "1" ]; then
-    rm tmpfile@$file_name
+    rm $WORK_LOCATION/tmpfile@$file_name
 fi
 exit 0
 
